"""Remove usename

Revision ID: 2a99369d5f17
Revises: 8234d4fc5c2a
Create Date: 2024-07-09 21:47:46.242271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a99369d5f17'
down_revision: Union[str, None] = '8234d4fc5c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cliente_username_key', 'cliente', type_='unique')
    op.drop_column('cliente', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_unique_constraint('cliente_username_key', 'cliente', ['username'])
    # ### end Alembic commands ###
