"""Adicionar o relacionamento de Cliente com ItemCarrinho

Revision ID: 378995dcf26d
Revises: 3b5795dc2e58
Create Date: 2024-07-11 11:37:16.272538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378995dcf26d'
down_revision: Union[str, None] = '3b5795dc2e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemCarrinho', sa.Column('cliente_cpf', sa.String(14), nullable=True))
    op.create_foreign_key(None, 'itemCarrinho', 'cliente', ['cliente_cpf'], ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itemCarrinho', type_='foreignkey')
    op.drop_column('itemCarrinho', 'cliente_cpf')
    # ### end Alembic commands ###
