"""Add tipo_entrega to aluguel

Revision ID: 3b5795dc2e58
Revises: 2a99369d5f17
Create Date: 2024-07-09 22:47:07.633053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b5795dc2e58'
down_revision: Union[str, None] = '2a99369d5f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluguel', sa.Column('tipo_entrega', sa.String(), nullable=False))
    op.drop_column('entrega', 'tipo_entrega')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrega', sa.Column('tipo_entrega', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('aluguel', 'tipo_entrega')
    # ### end Alembic commands ###
