"""Adiciona contrato em aluguel

Revision ID: 68d0c78c6b0c
Revises: f35527cd517e
Create Date: 2024-08-24 12:34:18.607416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d0c78c6b0c'
down_revision: Union[str, None] = 'f35527cd517e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluguel', sa.Column('contrato', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aluguel', 'contrato')
    # ### end Alembic commands ###
