"""adiciona total em ItemCarrinho

Revision ID: 69ce256d5712
Revises: 68d0c78c6b0c
Create Date: 2024-09-03 11:55:08.852131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ce256d5712'
down_revision: Union[str, None] = '68d0c78c6b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemCarrinho', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemCarrinho', 'total')
    # ### end Alembic commands ###
