"""Adiciona acess_token a Cliente

Revision ID: 78f9b144be4b
Revises: 69ce256d5712
Create Date: 2024-09-10 11:34:15.630306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f9b144be4b'
down_revision: Union[str, None] = '69ce256d5712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('acess_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'cliente', ['acess_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='unique')
    op.drop_column('cliente', 'acess_token')
    # ### end Alembic commands ###
