"""Add aluguel_id to ItemCarrinho

Revision ID: 8234d4fc5c2a
Revises: f41373163f61
Create Date: 2024-07-09 21:31:41.611857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8234d4fc5c2a'
down_revision: Union[str, None] = 'f41373163f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
